server:
  port: 4000

spring:
  cloud:
    gateway:
      routes:
        # ====================
        # Auth Service Route
        # ====================
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # ====================
        # Student Service Route (JWT Protected)
        # ====================
        - id: student-service-route
          uri: http://student-service:4001
          predicates:
            - Path=/api/students/**   # Route all student requests
          filters:
            - StripPrefix=1
            - name: JwtValidation   # Custom JWT validation filter

        # ====================
        # Attendance Service Route (JWT Protected)
        # ====================
        - id: attendance-service-route
          uri: http://attendance-service:5005
          predicates:
            - Path=/api/attendance/**  # Route all attendance requests
          filters:
            - StripPrefix=1
            - name: JwtValidation   # Custom JWT validation filter
